#!/usr/bin/env python3
"""Erzeugt packages/rtl-extra/src/zos/unxsockh.inc (Socket-Konstanten für die Unit
sockets) aus den z/OS-Headern (~/zos/include, ASCII). Die Namen stammen aus der
AIX-Fassung derselben Datei; übernommen wird, was z/OS definiert.

    gen-sockh.py [aix/unxsockh.inc] > zos/unxsockh.inc

Mehrfach unterschiedlich definierte Namen (je nach Feature-Makros) werden auf
stderr gemeldet und mit dem ersten Wert übernommen.
"""
import os
import re
import sys

INC = os.path.expanduser(os.environ.get("ZOS_INCLUDE", "~/zos/include"))
HEADERS = ["sys/socket.h", "netinet/in.h", "netinet/tcp.h", "sys/un.h", "netdb.h",
           "arpa/inet.h", "net/if.h"]
TEMPLATE = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    "~/src/fpc/packages/rtl-extra/src/aix/unxsockh.inc")

DEFINE = re.compile(r"^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.+?)\s*(?:/\*.*)?$")
defs = {}
conflicts = {}
for h in HEADERS:
    path = os.path.join(INC, h)
    if not os.path.exists(path):
        continue
    for line in open(path, errors="replace"):
        m = DEFINE.match(line)
        if not m:
            continue
        name, val = m.group(1), m.group(2).strip()
        if name in defs and defs[name] != val:
            conflicts.setdefault(name, {defs[name]}).add(val)
            continue
        defs.setdefault(name, val)


def evaluate(expr, depth=0):
    """Numerischen Wert eines Makros bestimmen (Zahlen, Namen, | + << ( ))."""
    if depth > 10:
        return None
    e = expr.strip()
    e = re.sub(r"\b(0[xX][0-9a-fA-F]+|\d+)[uUlL]*\b", r"\1", e)
    names = re.findall(r"\b[A-Za-z_][A-Za-z0-9_]*\b", e)
    for n in names:
        if n not in defs:
            return None
        v = evaluate(defs[n], depth + 1)
        if v is None:
            return None
        e = re.sub(r"\b%s\b" % n, str(v), e)
    if not re.fullmatch(r"[0-9xXa-fA-F\s|&+\-<>()~]*", e):
        return None
    try:
        return int(eval(e, {"__builtins__": {}}))
    except Exception:
        return None


names = []
for line in open(TEMPLATE, errors="replace"):
    m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=", line)
    if m and m.group(1) not in names:
        names.append(m.group(1))

out = []
missing = []
for n in names:
    v = evaluate(defs[n]) if n in defs else None
    if v is None:
        missing.append(n)
        continue
    out.append(f"  {n} = ${v:x};" if v > 9 else f"  {n} = {v};")
    if n in conflicts:
        print(f"Achtung {n}: mehrere Definitionen {sorted(conflicts[n])}", file=sys.stderr)

print("""{
   This file is part of the Free Pascal run time library.

   OS dependant part of the header of the sockets unit: z/OS.
   Generated by gen-sockh.py from the z/OS headers (sys/socket.h, netinet/in.h,
   netinet/tcp.h, ...); names from the AIX version of this file.

   See the file COPYING.FPC, included in this distribution,
   for details about the copyright.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY;without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
}

const""")
print("\n".join(out))
# fehlt auf z/OS, von fcl-net (fpsock) benutzt: kein Unterdrücken von SIGPIPE je Aufruf
print("  MSG_NOSIGNAL = 0;               { not on z/OS }")
print(f"\n{{ not defined on z/OS: {' '.join(missing)} }}" if missing else "")
print(f"{len(out)} Konstanten, {len(missing)} fehlen", file=sys.stderr)
