#!/bin/sh
# zos-sh: führt einen Befehl in der z/OS-UNIX-Shell aus (im Verzeichnis ZOS_DIR).
#   zos-sh 'befehl ...'
# Läuft in WSL (ssh.exe von Git für Windows) oder unter Linux (zos-hostenv.sh);
# Zugangsdaten aus .zos.env.
SELF=$(readlink -f "$0")
. "$(dirname "$SELF")/zos-hostenv.sh"
ENVFILE=${ZOS_ENV:-$(dirname "$SELF")/../.zos.env}
WH=$(zos_winhome)
HOME=$WH . "$ENVFILE"
exec $ZOS_SSH -i "$ZOS_KEY" -o BatchMode=yes "$ZOS_HOST" "cd $ZOS_DIR && $*"
